// Copyright (C) 2021  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and any partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details, at
// https://fpgasoftware.intel.com/eula.


// Generated by Quartus Prime Version 21.1 (Build Build 842 10/21/2021)
// Created on Mon Oct 27 18:06:41 2025

fixed_point_add_sub fixed_point_add_sub_inst
(
	.a(a_sig) ,	// input [15:0] a_sig
	.b(b_sig) ,	// input [15:0] b_sig
	.sum(sum_sig) ,	// output [15:0] sum_sig
	.diff(diff_sig) 	// output [15:0] diff_sig
);

